version: '3'
services:
  db:
    image: mongo:3.0.2
    network_mode: "host"
  directory_server:
    build: .
    ports:
     - "5001:5001"
  redis:
    image: "redis:alpine"
  file_server_1:
    build: .
    ports:
     - "5000:5000"
  redis:
    image: "redis:alpine"

    DIRECTORY_SERVER_PORT = "5001"
AUTHENTICATION_SERVER_PORT = "5002"
LOCK_SERVER_PORT = "5003"